# Site settings
title: ShutterForth
email: hello@shutterforth.co
description: > # this means to ignore newlines until "baseurl:"
  ShutterForth is a development journal about learning how to build things for the web. It features articles about web design, development, and the process of learning. It's written for my own edification, but if you learn something, too, then that's pretty cool.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shutterforth.co" # the base hostname & protocol for your site
twitter_username: shutterforth
github_username:  shutterforth

# Build settings
markdown: kramdown
kramdown:
  input: GFM
